# Base project configuration
project:
  name: "AI Demo"
  version: "1.0.0"
  api_prefix: "/api/v1"
  debug: true

# Database configuration
database:
  type: "postgresql"
  user: "odoo"
  password: "123456"
  host: "localhost"
  port: 5432
  db_name: "ai_demo"
  pool_size: 5
  pool_recycle: 3600

# Authentication configuration
auth:
  secret_key: "your-secret-key-here"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7

# CORS configuration
cors:
  origins:
    - "http://localhost:3000"
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

# Default admin account
admin:
  username: "admin"
  password: "admin123"
  email: "admin@example.com"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
  max_size: 10485760  # 10MB
  backup_count: 5 