# Development environment specific configuration
server:
  debug: true

database:
  host: localhost
  port: 5432
  name: ai_demo_dev
  user: postgres
  password: postgres

logging:
  level: DEBUG
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/app-dev.log 