# Development environment specific configuration
server:
  debug: true

database:
  type: "postgresql"
  host: "localhost"
  port: "5432"
  db_name: "ai_demo_dev"
  user: "postgres"
  password: "postgres"
  track_modifications: false
  pool_size: 5
  pool_recycle: 3600

logging:
  level: DEBUG
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/app-dev.log 