[project]
name = "ai-demo-dev"
version = "1.0.0"
description = "AI Demo Project Development Dependencies"
dependencies = [
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0",
    "pytest-asyncio>=0.23.0",
    "black>=24.1.0",
    "ruff>=0.2.0",
    "mypy>=1.8.0",
    "httpx>=0.26.0",
    "asgi-lifespan>=2.1.0"
] 